########################################################################
#                                                                      #
#                 The Ultimate Hide And Seek Plugin                    #
#                                                                      #
########################################################################
#                                                                      #
# By using this plugin, you automatically accept Minecraft EULA!       #
# If you have any problem, you can ask on our Discord for Support in   #
# channel #ðŸ“ƒâ”ƒhelp or by forum channel called #ðŸ“ˆâ”ƒsupport. If you      #
# found any bug, please report it. It'll help you and for our plugin!  #
#                                                                      #
########################################################################
#          Created by: Radekminecraft    and    FungY911               #
########################################################################


Core:
  No-Permission: "&c You donÂ´t have permissions." # Message displayed when a player does not have permission to use a command
  Prefix: "&8[&e&lH&e&&e&lS&8] &7>> &r" # Prefix for all messages from this plugin
  notEntity: "chod na server" # Message displayed when a player is not targeting a valid entity

Lobby:
  Success: "&7Lobby has been &a&lSUCCESSFULLY &7setuped&7!"
  Warning: "&eThe teleport on join is disabled! To enable it, set Lobby.onJoinLobby to true."
  onJoinLobby: true #When player joins server it teleports him to defined point
  onJoinX: 40.9 #X position of lobby spawn
  onJoinY: 140.6 #Y position of lobby spawn
  onJoinZ: 33.4 #Z position of lobby spawn
  onJoinPitch: 30.5
  onJoinYaw: 40.3
  onJoinWorldName: "world" #Name of the world
Reload:
  Reload-Message: "&cPlease wait, reloading plugin!"
  Successfully-Reloaded: "&aFiles arenas.yml, config.yml has beed reloaded!"

Create-Arena:
  Invalid-Message: "&cError! use command like this: /has createarena [arenaName] [arenaWorldName] [maxplayers] [minplayers] [seekersCount]"
  Created: "&aYour arena has been successfully created as %arena%!" # Use %arena% for show arena name
  Creating-Arena: "&7Please wait, alredy creating arena!"
  Arena-Exists: "&cError! Arena you created already exists!"

Database:
  # Type of database to use (options: MySQL, SQLite, Default: SQLite)
  Type: MySQL
  host: "localhost" # Hostname for MySQL database
  port: "3306" # Port for MySQL database
  username: "root" # Username for MySQL database
  database: "test" # Database name for MySQL
  password: "" # Password for MySQL database